
name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run triage
        run: |
          python src/triage_cli.py --csv data/emails.csv --out-dir outputs
      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: triage-report
          path: outputs/*
